export const LIGHT_THRESHOLDS = {
  DARKNESS: 0.3,
  TWILIGHT: 0.6,
  BRIGHT: 0.8,
} as const;

export const LIGHT_EFFECTS = {
  HEAL_RATE: 8,
  DAMAGE_RATE: 12,
  POWER_MULTIPLIER: 1.5,
  DARKNESS_DAMAGE_RESISTANCE: 0.5,
} as const;
