export interface RoomTheme {
  id: string;
  name: string;
  floorColor: number;
  wallColor: number;
  ceilingColor: number;
  ambientColor: number;
  ambientIntensity: number;
  fogColor: number;
  fogNear: number;
  fogFar: number;
  doorFrameColor: number;
  doorFrameWidth: number;
  hasArch: boolean;
  hasBars: boolean;
  torchColor: number;
  torchIntensity: number;
}

export const ROOM_THEMES: Record<string, RoomTheme> = {
  crypt: {
    id: 'crypt',
    name: 'Starting Crypt',
    floorColor: 0x1a1a28,
    wallColor: 0x2a2a3e,
    ceilingColor: 0x111118,
    ambientColor: 0x223344,
    ambientIntensity: 0.4,
    fogColor: 0x0d0d15,
    fogNear: 3,
    fogFar: 25,
    doorFrameColor: 0x4a4a5a,
    doorFrameWidth: 1.0,
    hasArch: true,
    hasBars: false,
    torchColor: 0x4466aa,
    torchIntensity: 1.5,
  },
  prison: {
    id: 'prison',
    name: 'Abandoned Prison',
    floorColor: 0x2a2222,
    wallColor: 0x3a3333,
    ceilingColor: 0x1a1515,
    ambientColor: 0x443322,
    ambientIntensity: 0.35,
    fogColor: 0x0d0a0a,
    fogNear: 4,
    fogFar: 28,
    doorFrameColor: 0x6a4a2a,
    doorFrameWidth: 0.8,
    hasArch: false,
    hasBars: true,
    torchColor: 0xff8844,
    torchIntensity: 2.0,
  },
  library: {
    id: 'library',
    name: 'Blood Library',
    floorColor: 0x2a1a1a,
    wallColor: 0x3a2222,
    ceilingColor: 0x1a0d0d,
    ambientColor: 0x662222,
    ambientIntensity: 0.5,
    fogColor: 0x1a0505,
    fogNear: 3,
    fogFar: 22,
    doorFrameColor: 0x8a2a2a,
    doorFrameWidth: 1.2,
    hasArch: true,
    hasBars: false,
    torchColor: 0xff3333,
    torchIntensity: 1.8,
  },
  sewer: {
    id: 'sewer',
    name: 'Sewer Network',
    floorColor: 0x1a2a1a,
    wallColor: 0x2a3a2a,
    ceilingColor: 0x0d1a0d,
    ambientColor: 0x224422,
    ambientIntensity: 0.3,
    fogColor: 0x051a05,
    fogNear: 2,
    fogFar: 20,
    doorFrameColor: 0x4a6a4a,
    doorFrameWidth: 0.9,
    hasArch: false,
    hasBars: false,
    torchColor: 0x44ff44,
    torchIntensity: 1.2,
  },
  chapel: {
    id: 'chapel',
    name: 'Forgotten Chapel',
    floorColor: 0x2a2a3a,
    wallColor: 0x3a3a4a,
    ceilingColor: 0x1a1a2a,
    ambientColor: 0x8888cc,
    ambientIntensity: 0.7,
    fogColor: 0x1a1a3a,
    fogNear: 5,
    fogFar: 35,
    doorFrameColor: 0xccaa44,
    doorFrameWidth: 1.3,
    hasArch: true,
    hasBars: false,
    torchColor: 0xffffaa,
    torchIntensity: 3.0,
  },
  torture: {
    id: 'torture',
    name: 'Torture Hall',
    floorColor: 0x2a1515,
    wallColor: 0x3a2020,
    ceilingColor: 0x1a0a0a,
    ambientColor: 0x551111,
    ambientIntensity: 0.3,
    fogColor: 0x1a0505,
    fogNear: 3,
    fogFar: 22,
    doorFrameColor: 0x5a2a1a,
    doorFrameWidth: 1.0,
    hasArch: false,
    hasBars: true,
    torchColor: 0xff4422,
    torchIntensity: 2.2,
  },
  ritual: {
    id: 'ritual',
    name: 'Ritual Chamber',
    floorColor: 0x1a1a3a,
    wallColor: 0x2a2a4a,
    ceilingColor: 0x0d0d2a,
    ambientColor: 0x4444aa,
    ambientIntensity: 0.6,
    fogColor: 0x05052a,
    fogNear: 4,
    fogFar: 30,
    doorFrameColor: 0x6a4aaa,
    doorFrameWidth: 1.1,
    hasArch: true,
    hasBars: false,
    torchColor: 0xaa44ff,
    torchIntensity: 2.5,
  },
  treasure: {
    id: 'treasure',
    name: 'Treasure Vault',
    floorColor: 0x2a2a1a,
    wallColor: 0x3a3a2a,
    ceilingColor: 0x1a1a0d,
    ambientColor: 0x887722,
    ambientIntensity: 0.6,
    fogColor: 0x1a1a05,
    fogNear: 4,
    fogFar: 28,
    doorFrameColor: 0xccaa22,
    doorFrameWidth: 1.2,
    hasArch: true,
    hasBars: false,
    torchColor: 0xffcc44,
    torchIntensity: 2.8,
  },
  antechamber: {
    id: 'antechamber',
    name: 'Boss Antechamber',
    floorColor: 0x2a2a3a,
    wallColor: 0x3a3a4a,
    ceilingColor: 0x1a1a2a,
    ambientColor: 0x6666aa,
    ambientIntensity: 0.5,
    fogColor: 0x1a1a2a,
    fogNear: 5,
    fogFar: 35,
    doorFrameColor: 0x8a8aaa,
    doorFrameWidth: 1.5,
    hasArch: true,
    hasBars: false,
    torchColor: 0xaaaaff,
    torchIntensity: 3.5,
  },
  boss: {
    id: 'boss',
    name: "Archbishop's Sanctum",
    floorColor: 0x3a3a4a,
    wallColor: 0x4a4a5a,
    ceilingColor: 0x2a2a3a,
    ambientColor: 0xaaaaff,
    ambientIntensity: 0.8,
    fogColor: 0x2a2a4a,
    fogNear: 8,
    fogFar: 50,
    doorFrameColor: 0xccccff,
    doorFrameWidth: 1.8,
    hasArch: true,
    hasBars: false,
    torchColor: 0xffffff,
    torchIntensity: 4.0,
  },
};

export const PROGRESSION_ORDER = [
  'crypt',
  'prison',
  'library',
  'sewer',
  'chapel',
  'torture',
  'ritual',
  'treasure',
  'antechamber',
  'boss',
] as const;

export function getThemeForRoom(roomIndex: number, _totalRooms: number): RoomTheme {
  const idx = Math.min(roomIndex, PROGRESSION_ORDER.length - 1);
  return ROOM_THEMES[PROGRESSION_ORDER[idx]];
}
