export const GAME_CONFIG = {
  FIXED_TIMESTEP: 1 / 60,
  MAX_FRAME_SKIP: 5,
  RENDER_DISTANCE: 100,
  PLAYER_SPEED: 5,
  PLAYER_SPRINT_MULTIPLIER: 1.5,
  CAMERA_OFFSET_Y: 6,
  CAMERA_OFFSET_Z: 8,
  CAMERA_LOOK_AHEAD: 3,
  CAMERA_SMOOTHING: 12,
} as const;
