export const LIGHT_CONFIG = {
  SENSOR_UPDATE_INTERVAL: 100,
  SENSOR_MIN_LUX: 0,
  SENSOR_MAX_LUX: 1000,
  NORMALIZE_DIVISOR: 1000,
  DARKNESS_HEAL_RATE: 8,
  LIGHT_DAMAGE_RATE: 12,
  TOGGLE_KEY: 'Space',
} as const;
